### PR TITLE
add scalability plot on the front page

### PR DESCRIPTION
**Pull request by qyx268**

### CODE REVIEW

**Review by andreimesinger — COMMENTED** [review]
can you please add a brief description of the plot...  also, not sure what is Human time...

**Comment by steven-murray** [comment]
@qyx268 I second @andreimesinger's request for a little description. Is "human time" in hours? What model is being run? 

Secondly, we'll need to get the linting/installing working in #45 before this will pass tests. I'll try to get to it asap.

**Comment by qyx268** [comment]
I've added a few lines for the plot. 

I feel it might make the front page too long if I also show what the test models are. So I just added a link to Issue #50.

**Comment by andreimesinger** [comment]
again the y axis is not immediately obvious what it means...  if i am understanding correctly what you mean, i would change the label to "Sampling rate (number of simulations per hour)" or somerhing like that

**Comment by steven-murray** [comment]
@qyx268 thanks for the updated text, that is helpful. I understand the y-axis now, so I'm happy, but @andreimesinger's suggestion of "Sampling Rate (simulations per human hour)" might be even more clear.

**Review by steven-murray — APPROVED** [review]

**Comment by qyx268** [comment]
should be alright now?

**Comment by steven-murray** [comment]
Looks good to me!

**Review by andreimesinger — APPROVED** [review]

**Pull request merged**
